config/routes.rb
Papa::Application.routes.draw do

  resources :clients do
collection do 
     post 'search'
end
  end

  resources :cortes

  resources :sales do
    member do 
      get 'pagar'
    end
  end

  resources :ventas

  resources :compra_categories

  resources :products

  resources :product_categories

  resources :compras

  resources :gastos

  resources :ventas

  resources :recetas
  
  resources :reports

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end

    if user.has_role? :caja
      can :manage, [Compra, Sale, Corte, Gasto]
      cannot [:read, :destroy, :update], Sale
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :name, :phone, :street, :street2, :district, :note, :latitude, :longitude

  validate :format_phone

  validates :phone, :presence => true
  
  def format_phone
    self.phone = self.phone.gsub(/[^0-9]/,"")
  end

end

app/models/compra.rb
class Compra < ActiveRecord::Base
  attr_accessible :name, :tipo, :medida, :avatar, :avatar_cache, :compra_category_id
  mount_uploader :avatar, AvatarUploader
  has_many :gastos
  belongs_to :compra_category

  def self.mas_comun
    comunes = []
    Gasto.mas_comun.each_pair do |c, v|
      comunes << c
    end
    return self.find(comunes)
  end

end

app/models/compra_category.rb
class CompraCategory < ActiveRecord::Base
  attr_accessible :name
end

app/models/corte.rb
class Corte < ActiveRecord::Base
  attr_accessible :user_id, :caja, :fecha
  has_many :sales
  has_many :gastos



  def count_recetas
    @recetas = { }

    self.sales.each do |sale|
      sale.sale_lines.each do |line|
        if line.product and line.product.receta
          line.product.receta.receta_lines.each do |receta|

            if @recetas[receta.compra.name].blank?
              @recetas[receta.compra.name] = receta.cantidad * line.cantidad if line.cantidad and receta.cantidad
            else
              @recetas[receta.compra.name] += receta.cantidad * line.cantidad if line.cantidad and receta.cantidad
            end
          end
        end
      end
    end
    return @recetas
  end

end

app/models/gasto.rb
class Gasto < ActiveRecord::Base
  attr_accessible :compra_id, :volumen, :precio, :fecha, :nota, :es_caja
  belongs_to :compra
  
  validates :compra_id, :presence => true
  validates :volumen, :presence => true
  validates :precio, :presence => true

  scope :no_corte, where(:corte_id => nil)

  scope :no_corte_caja, where(:corte_id => nil, :es_caja => true)

  scope :no_corte_no_caja, where(:corte_id => nil, :es_caja => false)
  
#  scope :mas_comun, order('count_id desc').group('compra_id').count('id')
  
  def name
    self.compra.name
  end

  def self.mas_comun
    self.order('count_id desc').group('compra_id').limit(6).count('id')
  end


end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :price, :product_category_id, :avatar, :avatar_cache
  mount_uploader :avatar, AvatarUploader
  belongs_to :product_category
  has_one :receta


  def self.no_receta
    todo = []
    self.all.each do  |producto|
      todo << producto if producto.receta.blank?
    end
    return todo
  end

end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
  attr_accessible :name, :parent_id, :avatar, :avatar_cache
  mount_uploader :avatar, AvatarUploader
  belongs_to :parent, :class_name => "ProductCategory", :foreign_key => "parent_id"
  has_many :products
  has_ancestry



end

app/models/receta.rb
class Receta < ActiveRecord::Base
  attr_accessible :name, :product_id, :receta_lines_attributes
  has_many :receta_lines
  belongs_to :product
  accepts_nested_attributes_for :receta_lines


end

app/models/receta_line.rb
class RecetaLine < ActiveRecord::Base
  attr_accessible :compra_id, :product_id, :cantidad, :receta_id
  belongs_to :receta
  belongs_to :product
  belongs_to :compra
  
end

app/models/report.rb
class Report
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  attr_accessible :client_id, :seller_id, :corte_id, :total, :sale_lines_attributes, :por_pagar, :nota
  has_many :sale_lines, :dependent => :destroy
  belongs_to :client

  accepts_nested_attributes_for :sale_lines

  scope :no_corte, where(:corte_id => nil)

  
  def sale_names
    nombres = []
    self.sale_lines.each do |line|
      if line.product.nil?
        nombres << line.valor.to_s
      else
      if line.cantidad > 1
        nombres << line.cantidad.to_s + "(" + line.product.name + ")"
      else
        nombres << line.product.name
      end
      end
    end
    return nombres.to_sentence
  end

end

app/models/sale_line.rb
class SaleLine < ActiveRecord::Base
  attr_accessible :cantidad, :descuento, :precio, :product_id, :sale_id, :valor
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :username, :name, :email, :password, :password_confirmation, :remember_me, :login
  attr_accessor :login

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

def is?(role)
  roles.include?(role.to_s)
end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.all
  end

  def show
    @client = Client.find(params[:id])
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(params[:client])
    if @client.save
      #redirect_to @client, :notice => "Successfully created client."
      render 'search'
    else
      render :action => 'new'
    end
  end

  def edit
    @client = Client.find(params[:id])
  end

  def search
    @client = Client.find_by_phone(params[:phone])

    respond_to do |format|
      format.js
    end

  end


  def update
    @client = Client.find(params[:id])
    if @client.update_attributes(params[:client])
      redirect_to @client, :notice  => "Successfully updated client."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @client = Client.find(params[:id])
    @client.destroy
    redirect_to clients_url, :notice => "Successfully destroyed client."
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/compras_helper.rb
module ComprasHelper
end

app/helpers/gastos_helper.rb
module GastosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/recetas_helper.rb
module RecetasHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/clients/_form.html.haml
.row
  .col-sm-6
    =form_for @client, :html => {:class => "form-horizontal"}, :remote => true do |f|
      .form-group
        =f.label "Tel", :class => "control-label col-xs-3"
        .col-xs-9
          =f.text_field :phone, :value => params[:phone], :class => "form-control"
      .form-group
        =f.label "Calle", :class => "control-label col-xs-3"
        .col-xs-9
          =f.text_field :street, :class => "form-control"
      .form-group
        =f.label "Calle2", :class => "control-label col-xs-3"
        .col-xs-9
          =f.text_field :street2, :class => "form-control"
      .form-group
        =f.label "Colonia", :class => "control-label col-xs-3"
        .col-xs-9
          =f.text_field :district, :class => "form-control"
      .form-group
        =f.label "Notas", :class => "control-label col-xs-3"
        .col-xs-9
          =f.text_field :note, :class => "form-control"
      .form-group
        =f.label "Nombre", :class => "control-label col-xs-3"
        .col-xs-9
          =f.text_field :name, :class => "form-control"
        =f.hidden_field :latitude
        =f.hidden_field :longitude
  .col-sm-6
    #map-canvas{ :style => "width: 100%; height: 200px"}

app/views/clients/_show.html.haml
.row
  .span2
    %strong Tel:
    =@client.phone
    -if !@client.name.blank?
      %br
      %strong Nombre:
      =@client.name
    -if !@client.note.blank?
      %br
      %strong Nota: 
      =@client.note 

  .span3
    =@client.street
    %br
    =@client.street2

.print_map=image_tag('http://maps.googleapis.com/maps/api/staticmap?center='+@client.latitude.to_s+','+@client.longitude.to_s+'&markers='+@client.latitude.to_s+','+@client.longitude.to_s+'&zoom=17&size=300x300&key=AIzaSyBUSvxOY77MsuaZXlpGUmL6RZcCuyq3F8Q&sensor=false')

app/views/clients/edit.html.haml
- title "Edit Client"

= render 'form'

%p
  = link_to "Show", @client
  |
  = link_to "View All", clients_path

app/views/clients/index.html.haml
%h1 Clients

%table
  %tr
    %th Name
    %th Phone
    %th Street
    %th Street2
    %th District
    %th Note
  - for client in @clients
    %tr
      %td= client.name
      %td= client.phone
      %td= client.street
      %td= client.street2
      %td= client.district
      %td= client.note
      %td= link_to 'Show', client
      %td= link_to 'Edit', edit_client_path(client)
      %td= link_to 'Destroy', client, :confirm => 'Are you sure?', :method => :delete

%p= link_to "New Client", new_client_path

app/views/clients/new.html.haml
%h1 New Client

= render 'form'

%p= link_to "Back to List", clients_path

app/views/clients/search.js.haml
-if @client
  $("#new_cliente").modal("hide");
  $("#client_id").val("#{@client.id}")
  $(".cliente").html("#{escape_javascript(render 'clients/show', :client => @client)}");


-else
  -@client = Client.new
  $("#new_cliente .modal-body").html("#{escape_javascript(render 'clients/form')}");
  initialize();
  $("#new_cliente").modal("show");
  google.maps.event.trigger(map, "resize");
  $('#client_street').change(function() {
  getAddress();
  });
  $('#client_district').change(function() {
  getAddress();
  });

app/views/clients/show.html.haml
- title "Client"

%p
  %strong Name:
  = @client.name
%p
  %strong Phone:
  = @client.phone
%p
  %strong Street:
  = @client.street
%p
  %strong Street2:
  = @client.street2
%p
  %strong District:
  = @client.district
%p
  %strong Note:
  = @client.note

%p
  = link_to "Edit", edit_client_path(@client)
  |
  = link_to "Destroy", @client, :confirm => 'Are you sure?', :method => :delete
  |
  = link_to "View All", clients_path