config/routes.rb
Papa::Application.routes.draw do

  resources :clients do
collection do 
     post 'search'
end
  end

  resources :cortes

  resources :sales do
    member do 
      get 'pagar'
    end
  end

  resources :ventas

  resources :compra_categories

  resources :products

  resources :product_categories

  resources :compras

  resources :gastos

  resources :ventas

  resources :recetas
  
  resources :reports

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end

    if user.has_role? :caja
      can :manage, [Compra, Sale, Corte, Gasto]
      cannot [:read, :destroy, :update], Sale
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :name, :phone, :street, :street2, :district, :note, :latitude, :longitude

  validate :format_phone

  validates :phone, :presence => true
  
  def format_phone
    self.phone = self.phone.gsub(/[^0-9]/,"")
  end

end

app/models/compra.rb
class Compra < ActiveRecord::Base
  attr_accessible :name, :tipo, :medida, :avatar, :avatar_cache, :compra_category_id
  mount_uploader :avatar, AvatarUploader
  has_many :gastos
  belongs_to :compra_category

  def self.mas_comun
    comunes = []
    Gasto.mas_comun.each_pair do |c, v|
      comunes << c
    end
    return self.find(comunes)
  end

end

app/models/compra_category.rb
class CompraCategory < ActiveRecord::Base
  attr_accessible :name
end

app/models/corte.rb
class Corte < ActiveRecord::Base
  attr_accessible :user_id, :caja, :fecha
  has_many :sales
  has_many :gastos



  def count_recetas
    @recetas = { }

    self.sales.each do |sale|
      sale.sale_lines.each do |line|
        if line.product and line.product.receta
          line.product.receta.receta_lines.each do |receta|

            if @recetas[receta.compra.name].blank?
              @recetas[receta.compra.name] = receta.cantidad * line.cantidad if line.cantidad and receta.cantidad
            else
              @recetas[receta.compra.name] += receta.cantidad * line.cantidad if line.cantidad and receta.cantidad
            end
          end
        end
      end
    end
    return @recetas
  end

end

app/models/gasto.rb
class Gasto < ActiveRecord::Base
  attr_accessible :compra_id, :volumen, :precio, :fecha, :nota, :es_caja
  belongs_to :compra
  
  validates :compra_id, :presence => true
  validates :volumen, :presence => true
  validates :precio, :presence => true

  scope :no_corte, where(:corte_id => nil)

  scope :no_corte_caja, where(:corte_id => nil, :es_caja => true)

  scope :no_corte_no_caja, where(:corte_id => nil, :es_caja => false)
  
#  scope :mas_comun, order('count_id desc').group('compra_id').count('id')
  
  def name
    self.compra.name
  end

  def self.mas_comun
    self.order('count_id desc').group('compra_id').limit(6).count('id')
  end


end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :price, :product_category_id, :avatar, :avatar_cache
  mount_uploader :avatar, AvatarUploader
  belongs_to :product_category
  has_one :receta


  def self.no_receta
    todo = []
    self.all.each do  |producto|
      todo << producto if producto.receta.blank?
    end
    return todo
  end

end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
  attr_accessible :name, :parent_id, :avatar, :avatar_cache
  mount_uploader :avatar, AvatarUploader
  belongs_to :parent, :class_name => "ProductCategory", :foreign_key => "parent_id"
  has_many :products
  has_ancestry



end

app/models/receta.rb
class Receta < ActiveRecord::Base
  attr_accessible :name, :product_id, :receta_lines_attributes
  has_many :receta_lines
  belongs_to :product
  accepts_nested_attributes_for :receta_lines


end

app/models/receta_line.rb
class RecetaLine < ActiveRecord::Base
  attr_accessible :compra_id, :product_id, :cantidad, :receta_id
  belongs_to :receta
  belongs_to :product
  belongs_to :compra
  
end

app/models/report.rb
class Report
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  attr_accessible :client_id, :seller_id, :corte_id, :total, :sale_lines_attributes, :por_pagar, :nota
  has_many :sale_lines, :dependent => :destroy
  belongs_to :client

  accepts_nested_attributes_for :sale_lines

  scope :no_corte, where(:corte_id => nil)

  
  def sale_names
    nombres = []
    self.sale_lines.each do |line|
      if line.product.nil?
        nombres << line.valor.to_s
      else
      if line.cantidad > 1
        nombres << line.cantidad.to_s + "(" + line.product.name + ")"
      else
        nombres << line.product.name
      end
      end
    end
    return nombres.to_sentence
  end

end

app/models/sale_line.rb
class SaleLine < ActiveRecord::Base
  attr_accessible :cantidad, :descuento, :precio, :product_id, :sale_id, :valor
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :username, :name, :email, :password, :password_confirmation, :remember_me, :login
  attr_accessor :login

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

def is?(role)
  roles.include?(role.to_s)
end
end

app/controllers/compras_controller.rb
class ComprasController < ApplicationController
load_and_authorize_resource
  def index
    @compras = Compra.all
    @comunes = Compra.mas_comun
  end

  def show
    @compra = Compra.find(params[:id])
  end

  def new
    @compra = Compra.new
  end

  def create
    @compra = Compra.new(params[:compra])
    if @compra.save
      redirect_to @compra, :notice => "Successfully created compra."
    else
      render :action => 'new'
    end
  end

  def edit
    @compra = Compra.find(params[:id])
  end

  def update
    @compra = Compra.find(params[:id])
    if @compra.update_attributes(params[:compra])
      redirect_to @compra, :notice  => "Successfully updated compra."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @compra = Compra.find(params[:id])
    @compra.destroy
    redirect_to compras_url, :notice => "Successfully destroyed compra."
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/compras_helper.rb
module ComprasHelper
end

app/helpers/gastos_helper.rb
module GastosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/recetas_helper.rb
module RecetasHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/compras/_form.html.haml
= form_for @compra do |f|
  %p
    = f.label :name
    = f.text_field :name
  %p
    = f.label 'Unidad de Medición'
    = f.text_field :medida
  %p
    =f.label :compra_category_id
    =f.select :compra_category_id, CompraCategory.all.collect {|p| [ p.name, p.id ]}

  %p
    = f.label :avatar
    =f.file_field :avatar
    =f.hidden_field :avatar_cache
  %p
    = f.submit

app/views/compras/edit.html.haml
%h1 Edit Compra

= render 'form'

%p
  = link_to "Show", @compra
  |
  = link_to "View All", compras_path

app/views/compras/index.html.haml
.row
  .col-sm-6
    %h1
      Compras
      -if current_user and current_user.has_role? :admin
        %small=link_to "New Compra", new_compra_path
  .col-sm-6
    %form
      %input.search-query.input-lg{:placeholder => "Busqueda", :type => "text", :id => 'search', :class => "form-control"}


.thumbnails.compras_thumbnails.well
  .row
    %h3 Compras comúnes
  .row
    -@comunes.each do |compra|
      .thumbnail.col-xs-4.col-sm-2
        =link_to(image_tag('icons/buy.png'), new_gasto_url + "?compra_id=" + compra.id.to_s, :remote => true, :class=>"icon")
        =link_to(raw('<i class="icon-trash"></i>'), compra, :confirm => 'Are you sure?', :method => :delete, :class => "pull-right")
        =link_to(raw('<i class="icon-edit"></i>'), edit_compra_path(compra), :class => "pull-right")

        =link_to(image_tag(compra.avatar_url(:thumb), :class => 'img-responsive avatar'), new_gasto_url + "?compra_id=" + compra.id.to_s, :remote => true, :class=>"icon")
        %span
          =link_to(compra.compra_category.name.capitalize + " -" + compra.name.capitalize, new_gasto_url + "?compra_id=" + compra.id.to_s, :remote => true)

=render 'shared/modal', :divid => "new_gasto", :title => "Registrar Compra"


%hr
.thumbnails.compras_thumbnails.well
  .row
    %h3 Todas las compras
  .row
    -@compras.each do |compra|
      .thumbnail.col-xs-4.col-sm-2
        =link_to(image_tag('icons/buy.png'), new_gasto_url + "?compra_id=" + compra.id.to_s, :remote => true, :class=>"icon")
        =link_to(raw('<i class="icon-trash"></i>'), compra, :confirm => 'Are you sure?', :method => :delete, :class => "pull-right")
        =link_to(raw('<i class="icon-edit"></i>'), edit_compra_path(compra), :class => "pull-right")

        =link_to(image_tag(compra.avatar_url(:thumb), :class => 'img-responsive avatar'), new_gasto_url + "?compra_id=" + compra.id.to_s, :remote => true, :class=>"icon")
        %span
          =link_to(compra.compra_category.name.capitalize + " -" + compra.name.capitalize, new_gasto_url + "?compra_id=" + compra.id.to_s, :remote => true)

=render 'shared/modal', :divid => "new_gasto", :title => "Registrar Compra"

app/views/compras/new.html.haml
%h1 New Compra

= render 'form'

%p= link_to "Back to List", compras_path

app/views/compras/show.html.haml
%h1 Compra

%p
  %strong Name:
  = @compra.name

%p
  = link_to "Edit", edit_compra_path(@compra)
  |
  = link_to "Destroy", @compra, :confirm => 'Are you sure?', :method => :delete
  |
  = link_to "View All", compras_path