config/routes.rb
Papa::Application.routes.draw do

  resources :clients do
collection do 
     post 'search'
end
  end

  resources :cortes

  resources :sales do
    member do 
      get 'pagar'
    end
  end

  resources :ventas

  resources :compra_categories

  resources :products

  resources :product_categories

  resources :compras

  resources :gastos

  resources :ventas

  resources :recetas
  
  resources :reports

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end

    if user.has_role? :caja
      can :manage, [Compra, Sale, Corte, Gasto]
      cannot [:read, :destroy, :update], Sale
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :name, :phone, :street, :street2, :district, :note, :latitude, :longitude

  validate :format_phone

  validates :phone, :presence => true
  
  def format_phone
    self.phone = self.phone.gsub(/[^0-9]/,"")
  end

end

app/models/compra.rb
class Compra < ActiveRecord::Base
  attr_accessible :name, :tipo, :medida, :avatar, :avatar_cache, :compra_category_id
  mount_uploader :avatar, AvatarUploader
  has_many :gastos
  belongs_to :compra_category

  def self.mas_comun
    comunes = []
    Gasto.mas_comun.each_pair do |c, v|
      comunes << c
    end
    return self.find(comunes)
  end

end

app/models/compra_category.rb
class CompraCategory < ActiveRecord::Base
  attr_accessible :name
end

app/models/corte.rb
class Corte < ActiveRecord::Base
  attr_accessible :user_id, :caja, :fecha
  has_many :sales
  has_many :gastos



  def count_recetas
    @recetas = { }

    self.sales.each do |sale|
      sale.sale_lines.each do |line|
        if line.product and line.product.receta
          line.product.receta.receta_lines.each do |receta|

            if @recetas[receta.compra.name].blank?
              @recetas[receta.compra.name] = receta.cantidad * line.cantidad if line.cantidad and receta.cantidad
            else
              @recetas[receta.compra.name] += receta.cantidad * line.cantidad if line.cantidad and receta.cantidad
            end
          end
        end
      end
    end
    return @recetas
  end

end

app/models/gasto.rb
class Gasto < ActiveRecord::Base
  attr_accessible :compra_id, :volumen, :precio, :fecha, :nota, :es_caja
  belongs_to :compra
  
  validates :compra_id, :presence => true
  validates :volumen, :presence => true
  validates :precio, :presence => true

  scope :no_corte, where(:corte_id => nil)

  scope :no_corte_caja, where(:corte_id => nil, :es_caja => true)

  scope :no_corte_no_caja, where(:corte_id => nil, :es_caja => false)
  
#  scope :mas_comun, order('count_id desc').group('compra_id').count('id')
  
  def name
    self.compra.name
  end

  def self.mas_comun
    self.order('count_id desc').group('compra_id').limit(6).count('id')
  end


end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :price, :product_category_id, :avatar, :avatar_cache
  mount_uploader :avatar, AvatarUploader
  belongs_to :product_category
  has_one :receta


  def self.no_receta
    todo = []
    self.all.each do  |producto|
      todo << producto if producto.receta.blank?
    end
    return todo
  end

end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
  attr_accessible :name, :parent_id, :avatar, :avatar_cache
  mount_uploader :avatar, AvatarUploader
  belongs_to :parent, :class_name => "ProductCategory", :foreign_key => "parent_id"
  has_many :products
  has_ancestry



end

app/models/receta.rb
class Receta < ActiveRecord::Base
  attr_accessible :name, :product_id, :receta_lines_attributes
  has_many :receta_lines
  belongs_to :product
  accepts_nested_attributes_for :receta_lines


end

app/models/receta_line.rb
class RecetaLine < ActiveRecord::Base
  attr_accessible :compra_id, :product_id, :cantidad, :receta_id
  belongs_to :receta
  belongs_to :product
  belongs_to :compra
  
end

app/models/report.rb
class Report
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  attr_accessible :client_id, :seller_id, :corte_id, :total, :sale_lines_attributes, :por_pagar, :nota
  has_many :sale_lines, :dependent => :destroy
  belongs_to :client

  accepts_nested_attributes_for :sale_lines

  scope :no_corte, where(:corte_id => nil)

  
  def sale_names
    nombres = []
    self.sale_lines.each do |line|
      if line.product.nil?
        nombres << line.valor.to_s
      else
      if line.cantidad > 1
        nombres << line.cantidad.to_s + "(" + line.product.name + ")"
      else
        nombres << line.product.name
      end
      end
    end
    return nombres.to_sentence
  end

end

app/models/sale_line.rb
class SaleLine < ActiveRecord::Base
  attr_accessible :cantidad, :descuento, :precio, :product_id, :sale_id, :valor
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :username, :name, :email, :password, :password_confirmation, :remember_me, :login
  attr_accessor :login

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

def is?(role)
  roles.include?(role.to_s)
end
end

app/controllers/sales_controller.rb
# -*- coding: utf-8 -*-
class SalesController < ApplicationController
load_and_authorize_resource
  def index
    @sales = Sale.order('created_at desc')
    
    @sales_pagar = Sale.where(:por_pagar => true)

  end

  def show
    @sale = Sale.find(params[:id])
  end

  def new
    @sale = Sale.new
    @product_categories = ProductCategory.roots
  end

  def create
    @sale = Sale.new(params[:sale])
    @sale.seller_id = current_user.id if current_user
 

    if @sale.save
      @sale.update_attribute(:total, @sale.sale_lines.sum(:valor))

      redirect_to new_sale_url, :notice => "¡Venta Registrada! ¡Tu muy bien! :)"
    else
      render :action => 'new'
    end
  end

  def edit
    @sale = Sale.find(params[:id])
    @product_categories = ProductCategory.roots

  end

  def update
    @sale = Sale.find(params[:id])
    @sale.seller_id = current_user.id if current_user


    if @sale.update_attributes(params[:sale])
      @sale.update_attribute(:total, @sale.sale_lines.sum(:valor))
      redirect_to @sale, :notice  => "Successfully updated sale."
    else
      render :action => 'edit'
    end
  end
  
  def pagar
    @sale = Sale.find(params[:id])
    @sale.update_attribute(:por_pagar, false)
    redirect_to sales_url
  end

  def destroy
    @sale = Sale.find(params[:id])
    @sale.destroy
    redirect_to :back, :notice => "Se ha cancelado la venta."
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/compras_helper.rb
module ComprasHelper
end

app/helpers/gastos_helper.rb
module GastosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/recetas_helper.rb
module RecetasHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.haml
-letras = ['Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I']
.row
  .col-sm-2.info_store
    %h1 Rico Don Pollo
    Sierra de Mazamitla #5814
    %br
    36-32-19-53
    %br
    %br
    Recibo de Venta
    %br
    =Time.now.strftime("%d/%m/%Y %H:%M")

  .col-sm-3.cliente_search
    =form_for(Client.new, :url => search_clients_path, :remote => true) do |f|
      .input-group
        =text_field_tag "phone", '', :class=>"form-control", :id => "appendedInputButtons"
        %span.input-group-btn
          =button_tag 'Search', :class => "btn btn-default", :type => "submit"
  .cliente.col-sm-5


=nested_form_for @sale, :html => {:class => 'sale_form'} do |f|

  =f.hidden_field :client_id, :id => "client_id"
  =f.hidden_field :total
  =f.hidden_field :por_pagar

  .row
    .col-lg-8.col-md-8.col-xs-12
      #sale_list
        .col-xs-12
          .row.sale_head
            .col-sm-4.col-xs-2
              Artículo
            .col-xs-2.center_text
              Precio
            .col-xs-2.center_text
              Cant.
            .col-xs-2.center_text
              Valor



        =f.fields_for :sale_lines do |line_form|
          .col-xs-12
            .row
              .col-sm-4.col-xs-2.p_name
                blabla
              .col-xs-2.precio.center_text
                $12.00
              .col-xs-2.cantidad.center_text
                3
              .col-xs-2.valor.center_text
                $23
              .col-xs-2.remove
                =line_form.hidden_field :product_id, :class => "f_product"
                =line_form.hidden_field :precio, :class => "f_precio"
                =line_form.hidden_field :cantidad, :class => "f_cantidad"
                =line_form.hidden_field :valor, :class => "f_valor"
                =line_form.link_to_remove "X"


        =f.link_to_add "Add a task", :sale_lines, :style => "display: none"

      .pull-left
        =f.text_area :nota, :class => "form-control"
      .total Total: <span>0.0</span>

      .p_paga Paga con: <span>0.0</span>
      .p_cambio Cambio: <span>0.0</span>

    .cliente.p_cliente
    #numpad.col-lg-3.col-md-3.col-sm-3
      %table.col-xs-12
        %tr
          %td{:colspan=>"4"}
            =text_field_tag 'display', '', :class => "form-control"
        %tr
          %td{:colspan=>"2"}
            %button.btn.btn-large.btn-default.empty_display{:type=>"button"} CE
          %td
            %button.btn.btn-large.btn-default{:type=>"button"} *
          %td
            %button.btn.btn-large.btn-default.minus{:type=>"button"} -
        %tr
          %td
            %button.btn.btn-large.btn-default.number.siete{:type=>"button"} 7
          %td
            %button.btn.btn-large.btn-default.number.ocho{:type=>"button"} 8
          %td
            %button.btn.btn-large.btn-default.number.nueve{:type=>"button"} 9
          %td{:rowspan=>"2"}
            %button.btn.btn-large.btn-default.double.plus{:type=>"button"} +
        %tr
          %td
            %button.btn.btn-large.btn-default.number.cuatro{:type=>"button"} 4
          %td
            %button.btn.btn-large.btn-default.number.cinco{:type=>"button"} 5
          %td
            %button.btn.btn-large.btn-default.number.seis{:type=>"button"} 6
        %tr
          %td
            %button.btn.btn-large.btn-default.number.uno{:type=>"button"} 1
          %td
            %button.btn.btn-large.btn-default.number.dos{:type=>"button"} 2
          %td
            %button.btn.btn-large.btn-default.number.tres{:type=>"button"} 3
          %td{:rowspan=>"2"}
            %button.btn.btn-large.btn-default.double.enter{:type=>"button", :onclick => "$('#pago_modal').modal('show')"} =

        %tr
          %td{:colspan=>"2"}
            %button.btn.btn-large.btn-default.number.cero{:type=>"button"} 0
          %td
            %button.btn.btn-large.btn-default.punto{:type=>"button"} .





  .row
    #menu_list.col-lg-12.col-md-12.col-sm-12.col-xs-12
      .main_menu.well
        .thumbnails
          .row
            .col-xs-12
              %h3 Principal
          .row
            .col-xs-12
              -@product_categories.each_with_index do |pc, index|
                .thumbnail.main_thumbnail.col-md-1.col-lg-1.col-sm-1.col-xs-2{:id => "main" + pc.id.to_s, :rel => pc.id, :class => 'option_' + index.to_s }
                  .letra=letras[index]
                  =image_tag(pc.avatar_url(:thumb), :class => 'img-polaroid')
                  =pc.name

      -@product_categories.each do |pc|
        %div{:class => "submenu well pc" + pc.id.to_s}


          .thumbnails
            .row
              .col-xs-12
                %button.btn.btn-large.back_main.pull-left{:type=>"button"}=image_tag('icons/up.png') + " Regresar"
                %h3.pull-left=pc.name

            .row
              .col-xs-12
                -pc.products.each_with_index do |product, index|
                  .thumbnail.col-md-1.col-lg-1.col-sm-1.col-xs-2{:name => product.name, :price => product.price, :product_id => product.id, :class => 'option_' + index.to_s }
                    .letra=letras[index]
                    =image_tag(product.avatar_url(:thumb), :class => 'img-polaroid')
                    =product.name

#pago_modal.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
        %h3 Pago
      .modal-body
        #moneypad
          .total.pull-left
            %p
              Total a pagar: <span>$0.0 </span>
          .clearfix
          %table
            %tr
              %td
                %button.btn.btn-large.number{:type=>"button"} $500
              %td
                %button.btn.btn-large.number{:type=>"button"} $200
              %td
                %button.btn.btn-large.number{:type=>"button"} $100
              %td
                %button.btn.btn-large.number{:type=>"button"} $50
              %td
                %button.btn.btn-large.number{:type=>"button"} $20
            %tr
              %td
                %button.btn.btn-large.number{:type=>"button"} $10
              %td
                %button.btn.btn-large.number{:type=>"button"} $5
              %td
                %button.btn.btn-large.number{:type=>"button"} $2
              %td
                %button.btn.btn-large.number{:type=>"button"} $1
              %td
                %button.btn.btn-large.number{:type=>"button"} $0.50
            %tr
              %td{:colspan=>"2"}
                %button.btn.btn-large.empty_money{:type=>"button"} CE
          .dado.pull-left
            Dado: <span>$0.0</span>
          .cambio.pull-right
            Cambio: <span>$0.0</span>
          .clearfix


      .modal-footer
        %button.btn{:onclick => "$('.modal').modal('hide'); window.print()"} Imprimir
        %button.btn{:onclick => "$('#sale_por_pagar').val('true'); $('.modal').modal('hide'); window.print(); $('.sale_form').submit();"}Domicilio
        %button.btn.btn-primary.pagar_btn{:onclick => "$('.modal').modal('hide'); window.print(); $('.sale_form').submit();"} Pagar



#new_cliente.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
        %h4.modal-title Cliente
      .modal-body
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Cerrar
        %button.btn.btn-primary{:type => "button", :onclick => "$(this).hide(); $('#new_cliente form').submit();"} Guardar

app/views/sales/edit.html.haml
= render 'form'

%p
  = link_to "Show", @sale
  |
  = link_to "View All", sales_path

app/views/sales/index.html.haml
%h1 Sales

-if !@sales_pagar.blank?
  %h4 Pagos Pendientes

  %table.table.bordered-table
    %tr
      %th Día
      %th Cliente
      %th Total
      %th
    - for sale in @sales_pagar
      %tr
        %td= sale.created_at.strftime("%d/%m/%Y %H:%M")
        %td
          =sale.client.phone if sale.client
          %br
          =sale.client.street if sale.client
        %td= sale.total
        %td=link_to("Pagar", pagar_sale_path(sale.id))


%table.table.bordered-table
  %tr
    %th Día
    %th Total
    %th
    %th
    %th
  - for sale in @sales
    %tr
      %td= sale.created_at.strftime("%d/%m/%Y %H:%M")
      %td= sale.total
      %td= link_to 'Show', sale
      %td= link_to 'Edit', edit_sale_path(sale)
      %td= link_to 'Destroy', sale, :confirm => 'Are you sure?', :method => :delete

%p= link_to "New Sale", new_sale_path

app/views/sales/new.html.haml
= render 'form'

app/views/sales/show.html.haml
%h1 Sale

%p
  %strong Cliente:
  = @sale.cliente_id
%p
  %strong Seller:
  = @sale.seller_id
%p
  %strong Corte:
  = @sale.corte_id

%p
  = link_to "Edit", edit_sale_path(@sale)
  |
  = link_to "Destroy", @sale, :confirm => 'Are you sure?', :method => :delete
  |
  = link_to "View All", sales_path